version: '3.8'

services:
  latece-site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
        DATABASE_URL: ${DATABASE_URL}
    container_name: latece-site
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    restart: unless-stopped